### ISSUE TITLE
xzy1 has 1 and xyz2 has 230k pointcloud? 

### ISSUE THREAD

**Issue by eashratj** [omron-sinicx/EdgeSelectiveFeatureWeaving#2]
In the provided training data :
Keys:  ['xyz1', 'xyz2'] xzy1: (1024, 3) Dataset_xyz1: , Shape: (1024, 3), Dtype: float32
& xzy2: (230000, 1024, 3) Dataset_xyz2: , Shape: (230000, 1024, 3), Dtype: float32 I think i am not being able to understand the dataset structure! why xyz1 has only 1 point cloud and xyz2 has 230k ? i would be really grateful if anyone can explain me that !

**Comment by AtsushiHashimoto** [comment]
@eashratj 
Thank you for your interest in our work. Although I'm just a second author and not quite clear about the program details, could you provide more specific information? For example, a link to the line you felt suspicious would help us greatly. In addition, the dataset is originally from the CorrNet3D paper, and our code is almost identical with their repository in the dataloader. Thus, I'm afraid that you could ask the same question in [the original github project](https://github.com/ZENGYIMING-EAMON/CorrNet3D).
